apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-api
  annotations:
    # The appropriate annotation will be selected based on cloud provider
    eks.amazonaws.com/role-arn: "${AWS_IAM_ROLE_ARN}"
    azure.workload.identity/client-id: "${AZURE_WORKLOAD_IDENTITY_CLIENT_ID}"
    iam.gke.io/gcp-service-account: "${GCP_SERVICE_ACCOUNT_EMAIL}"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-training
  annotations:
    # The appropriate annotation will be selected based on cloud provider
    eks.amazonaws.com/role-arn: "${AWS_TRAINING_IAM_ROLE_ARN}"
    azure.workload.identity/client-id: "${AZURE_TRAINING_WORKLOAD_IDENTITY_CLIENT_ID}"
    iam.gke.io/gcp-service-account: "${GCP_TRAINING_SERVICE_ACCOUNT_EMAIL}"