apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-api-metrics
  namespace: monitoring
  labels:
    prometheus: service-monitor
    app: model-api
spec:
  selector:
    matchLabels:
      app: model-api
  namespaceSelector:
    matchNames:
      - ml-deploy
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
  - port: http
    interval: 30s
    path: /model-metrics
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: '(model_.*)'
      action: keep

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ml-model-alerts
  namespace: monitoring
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
  - name: ml.rules
    rules:
    - alert: ModelPredictionLatencyHigh
      expr: histogram_quantile(0.95, sum(rate(model_prediction_latency_seconds_bucket[5m])) by (le, model_version)) > 0.5
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Model prediction latency is high"
        description: "95th percentile of prediction latency for {{ $labels.model_version }} is > 500ms for 10m"
    
    - alert: ModelErrorRateHigh
      expr: sum(rate(model_prediction_errors_total[5m])) by (model_version) / sum(rate(model_predictions_total[5m])) by (model_version) > 0.05
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Model error rate is high"
        description: "Error rate for {{ $labels.model_version }} is > 5% for 5m"
        
    - alert: ModelDriftDetected
      expr: abs(model_feature_drift_score) > 0.3
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Model drift detected"
        description: "Feature drift score for {{ $labels.feature }} in {{ $labels.model_version }} is {{ $value }}"