# Prometheus Configuration (prometheus.yml)

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ml_model_monitoring'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']