apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-key-vault-secrets
  namespace: ml-deploy
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${MANAGED_IDENTITY_CLIENT_ID}"
    keyvaultName: "${KEY_VAULT_NAME}"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: postgres-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: redis-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: minio-access-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: minio-secret-key
          objectType: secret
          objectVersion: ""
    tenantId: "${TENANT_ID}"
  secretObjects:
  - secretName: database-credentials
    type: Opaque
    data:
    - objectName: postgres-password
      key: password
  - secretName: redis-credentials
    type: Opaque
    data:
    - objectName: redis-password
      key: password
  - secretName: minio-credentials
    type: Opaque
    data:
    - objectName: minio-access-key
      key: access_key
    - objectName: minio-secret-key
      key: secret_key