# Service Account for model-api with appropriate IAM role annotations
apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-api
  namespace: ml-deploy
  annotations:
    # Cloud provider specific annotations
    # AWS
    eks.amazonaws.com/role-arn: "${AWS_IAM_ROLE_ARN}"
    # GCP
    iam.gke.io/gcp-service-account: "${GCP_SERVICE_ACCOUNT_EMAIL}"
    # Azure
    azure.workload.identity/client-id: "${AZURE_CLIENT_ID}"
---
# RBAC configuration for the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: model-api-role
  namespace: ml-deploy
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: model-api-role-binding
  namespace: ml-deploy
subjects:
- kind: ServiceAccount
  name: model-api
  namespace: ml-deploy
roleRef:
  kind: Role
  name: model-api-role
  apiGroup: rbac.authorization.k8s.io