apiVersion: v1
kind: ResourceQuota
metadata:
  name: ml-deploy-quota
  namespace: ml-deploy
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    requests.storage: 500Gi
    persistentvolumeclaims: "20"
    limits.cpu: "32" 
    limits.memory: 64Gi
    pods: "30"
    services: "15"
    configmaps: "30"
    secrets: "30"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: ml-deploy-limits
  namespace: ml-deploy
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 50m
      memory: 64Mi
    type: Container