apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: model-api-pdb
  namespace: ml-deploy
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: model-api
      component: inference