apiVersion: v1
kind: Service
metadata:
  name: model-api
  namespace: ml-deploy
  labels:
    app: model-api
    component: inference
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: model-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-api-ingress
  namespace: ml-deploy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  tls:
  - hosts:
    - api.ml-deploy.example.com
    secretName: model-api-tls
  rules:
  - host: api.ml-deploy.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: model-api
            port:
              number: 8000
