apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ml-deploy-vault-secret-provider
  namespace: ml-deploy
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault.example.com:8200"
    roleName: "ml-deploy-role"
    objects: |
      - objectName: "db-credentials"
        secretPath: "secret/ml-deploy/database"
        secretKey: "credentials.json"
      - objectName: "api-key"
        secretPath: "secret/ml-deploy/api"
        secretKey: "api_key"
      - objectName: "model-secrets"
        secretPath: "secret/ml-deploy/model"
        secretKey: "model_parameters.json"
  secretObjects:
    - secretName: db-credentials-secret
      type: Opaque
      data:
        - objectName: "db-credentials"
          key: credentials.json
    - secretName: api-key-secret
      type: Opaque
      data:
        - objectName: "api-key"
          key: api_key
    - secretName: model-secrets
      type: Opaque
      data:
        - objectName: "model-secrets"
          key: model_parameters.json